---
all:
  children:
    CVP:
      hosts:
       cv_ztp:
          ansible_host: 198.18.99.90
          ansible_user: root       
          ansible_password: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                33646364613263323736633437666466653437653539326433613436356434376161653533323532
                3632643730633235316332626464303438376237626531370a373661343963616365303765363336
                30336632613830373465376434313965383061613261656237643433346165393338356638613337
                3733313561386332330a366435346135383139303162636233313133373965383966343363626239
                3036    
       cv_server:
          ansible_httpapi_host: 198.18.99.90
          ansible_host: 198.18.99.90
          ansible_user: cvpadmin
          ansible_password:  !vault |
                $ANSIBLE_VAULT;1.1;AES256
                34656437363832333037653935326536303266313331373630366632313231353162323661303431
                6265653963353936666430306338366336373834396139330a653033393834656534316435663138
                37643932666463626530643232393836373532643064363965616134383233633238663665633365
                3035376632653366390a616130653732356331313864313332663965633636366232363638623335
                3563
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)   

# AVD_Fabric - EVPN Fabric running in home lab
    US_DC:
      children:
        SJ_FABRIC:
          children:
            SJ_SPINES:
              vars:
                type: spine
              hosts:
                SJ-SPINE1:
                  ansible_host: 198.18.99.101
                SJ-SPINE2:
                  ansible_host: 198.18.99.102
            SJ_L3LEAFS:
              vars:
                type: l3leaf
              children:
                SJ_LEAF1_2:
                  hosts:
                    SJ-LEAF1:
                      ansible_host: 198.18.99.103
                    SJ-LEAF2:
                      ansible_host: 198.18.99.104
                SJ_LEAF3_4:
                  hosts:
                    SJ-LEAF3:
                      ansible_host: 198.18.99.105
                    SJ-LEAF4:
                      ansible_host: 198.18.99.105
                SJ_DCI1_2:
                  hosts:
                    SJ-DCI1:
                      ansible_host: 198.18.99.107
                    SJ-DCI2:
                      ansible_host: 198.18.99.108
                      
        AS_FABRIC:
          children:
            AS_SPINES:
              vars:
                type: spine
              hosts:
                AS-SPINE1:
                  ansible_host: 198.18.98.101
                AS-SPINE2:
                  ansible_host: 198.18.98.102
            AS_L3LEAFS:
              vars:
                type: l3leaf
              children:
                AS_LEAF1_2:
                  hosts:
                    AS-LEAF1:
                      ansible_host: 198.18.98.103
                    AS-LEAF2:
                      ansible_host: 198.18.98.104
                AS_LEAF3_4:
                  hosts:
                    AS-LEAF3:
                      ansible_host: 198.18.98.105
                    AS-LEAF4:
                      ansible_host: 198.18.98.106
                AS_DCI1_2:
                  hosts:
                    AS-DCI1:
                      ansible_host: 198.18.98.107
                    AS-DCI2:
                      ansible_host: 198.18.98.108                      
 
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: ansible
            # should use vault for passwords
            ansible_ssh_pass: ansible
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false

        SJ_NETWORKS:
          children:
            SJ_L3LEAFS:

        SJ_ENDPOINTS:
          children:
            SJ_L3LEAFS:
            
        AS_NETWORKS:
          children:
            AS_L3LEAFS:

        AS_ENDPOINTS:
          children:
            AS_L3LEAFS:


