---  
 
servers: 
  endpoint30:
    adapters:
      - endpoint_ports: [G1/0/1, G1/0/2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [SJ-LEAF1, SJ-LEAF2]
        profile: SERVER_TRUNK
        port_channel:
          mode: active
          description: Endpoint 30 Port-channel
          lacp_fallback:
            mode: static  

  endpoint31:
    adapters:
      - endpoint_ports: [G1/0/1, G1/0/2]
        switch_ports: [Ethernet6, Ethernet6]
        switches: [SJ-LEAF3, SJ-LEAF3]
        profile: SERVER_TRUNK
        port_channel:
          mode: active
          description: Endpoint 31 Port-channel
          lacp_fallback:
            mode: static

network_ports:
  - switches:
      - SJ-BL.
    switch_ports:
      - Ethernet5
    vlans: 210-240
    description: To DCI Switches
    profile: DCI_TRUNK
