l3_edge:
  p2p_links_ip_pools:
    DCI1: 10.255.250.2/31
    DCI2: 10.255.250.4/31

  p2p_links:
    - id: 1
      ip_pool: DCI1
      subnet: 10.255.250.2/31
      nodes: [SJ-DCI1, AS-DCI1]
      interfaces: [Ethernet5, Ethernet5]
      as: [65002, 65102]
      include_in_underlay_protocol: true 
    
    - id: 2
      ip_pool: DCI2
      subnet: 10.255.250.4/31
      nodes: [SJ-DCI2, AS-DCI2]
      interfaces: [Ethernet5, Ethernet5]
      as: [65002, 65102]
      include_in_underlay_protocol: true   
